#!/usr/bin/env bash
#
# Settings

SHOCK2=${SHOCK2:=ss2}
THIEF1=${THIEF1:=t1}
THIEF2=${THIEF2:=t2}

SHOCK2_GAMESYS=${SHOCK2_GAMESYS:=shockscp.gam}
THIEF1_GAMESYS=${THIEF1_GAMESYS:=dark.gam}
THIEF2_GAMESYS=${THIEF2_GAMESYS:=dark.gam}

# Implementation

set -e

function main {
  local cmds=()
  while [[ $1 ]]; do
    if [[ $1 == -- ]]; then
      shift; break
    elif [[ $1 == -* ]]; then
      break
    else
      cmds+=("$1")
      shift
    fi
  done

  for cmd in "${cmds[@]}"; do
    echo "build/$cmd"
    build/$cmd "$@"
  done
}

function build/clean {
  git clean -fx maps/
}

function build/ss2 {
	mkmaps ss2 shockscp.gam "$@"
}

function build/t1 {
  mkmaps t1 dark.gam "$@"
}

function build/t2 {
  mkmaps t2 dark.gam "$@"
}

function build/test {
  mkmaps $SHOCK2/{earth,eng2,medsci1,hydro1,many}.mis
}

function build/all {
  build/clean
  build/ss2
  build/t1
  build/t2
  build/zip
}

function build/deploy {
	rsync -aPhv maps/ funkyhorror:www/toxicfrog/maps/
}

function build/zip {
	cd maps
  for game in *; do
    [[ -e $game/map.html ]] || continue
    echo -n "${game}-maps.zip: "
    rm -rf "zips/${game}-maps.zip"
    zip -9qr "zips/${game}-maps.zip" "${game}"
    echo "done."
  done
}

function mkmaps {
  local game="$1"
  local gamesys="$2"
  shift 2

  # FIXME: generalize strings, if they are useful for anything in T1/T2 -- book
  # and scroll titles, maybe?
  mkdir -p maps/$game
  ./mishtml \
    --gamedir $game \
    --propformat $game \
    --gameinfo gameinfo/$game-objects.lua,gameinfo/$game-maps.lua \
    --strings ss2/strings \
    --html-out maps/$game \
    "$@" &

  wait
}

[[ $1 ]] || set -- all
main "$@"
