#!/usr/bin/env lua
require 'util'
local vstruct = require 'vstruct'
local tagfile = require 'db.tagfile'
local proplist = require 'db.proplist'

flags.register('help', 'h', '?') {
  help = 'display this text';
}

flags.register('gamesys') {
  help = 'path to gamesys, e.g. shock.gam';
  type = flags.string;
}

flags.register('proplist') {
  help = 'path to proplist.txt generated by in-game :dump_props_full command';
  type = flags.string;
}

local function main(...)
  local args = flags.parse {...}
  if args.help or #args < 1 then
    print('Usage: mismap [flags] [--gamesys=shock.gam] map.mis')
    print(flags.help())
    os.exit(1)
  end

  if args.proplist then
    proplist.load(args.proplist)
  else
    print('WARNING: no --proplist specified, entity property data will be unavailable')
  end

  local gam; if args.gamesys then gam = tagfile(args.gamesys) end
  local mis = tagfile(args[1], gam)

  return mis
end

if love then
  require 'love2d' (main)
else
  return main(...)
end
