#!/usr/bin/env bash
#
# Wrapper script for the HTML map generator.

SRCDIR="$(dirname "$0")"

if [[ $LOVE2D ]]; then
  : pass
elif type love >/dev/null 2>/dev/null; then
  LOVE2D=love
else
  >&2 echo "Couldn't find 'love' command, please make sure love2d is installed"
  exit 1
fi

export MISMAP_MAIN="main.mishtml"
exec love "$SRCDIR" \
  --html-in="$SRCDIR/res" \
  "$@"
