#!/usr/bin/env bash
#
# Wrapper script for mislist. Sets up LUA_PATH etc before invoking it.

SRCDIR="$(dirname "$0")"
export LUA_PATH="$SRCDIR/?.lua;$SRCDIR/?/init.lua;;"

if [[ $LUA ]]; then
  : pass
elif type luajit >/dev/null 2>/dev/null; then
  LUA=luajit
elif type lua >/dev/null 2>/dev/null; then
  >&2 echo "Couldn't find luajit, falling back to plain lua. Good luck!"
  LUA=lua
else
  >&2 echo "Couldn't find luajit or lua, aborting."
  exit 1
fi

exec $LUA "$SRCDIR/main/mislist.lua" "$@"
